export const GENRES = [
    "Akcja",
    "Animowany",
    "Biograficzny",
    "Dramat",
    "Dokumentalny",
    "Familijny",
    "Fantastyczny",
    "Gangsterski",
    "Historyczny",
    "Horror",
    "Komedia",
    "Kostiumowy",
    "Kryminalny",
    "Melodramat",
    "Muzyczny",
    "Noir",
    "Przygodowy",
    "Romantyczny",
    "Science-Fiction",
    "Sensacyjny",
    "Sztuk Walki",
    "Thriller",
    "Western",
    "Wojenny"
]
